### ISSUE TITLE
npm run deploy not working

### ISSUE THREAD

**Issue by BartusZak** [rpidanny/serverless-cognito-boilerplate#6]
> Executing task: npm run deploy <
> 
> 
> > serverless-cognito-boilerplate@0.1.0 deploy C:\Users\bploszynski\Documents\GitLab\serverless-cognito-boilerplate
> > npm run test:coverage && export SLS_DEBUG=* && serverless deploy
> 
> 
> > serverless-cognito-boilerplate@0.1.0 test:coverage C:\Users\bploszynski\Documents\GitLab\serverless-cognito-boilerplate
> > standard && istanbul cover _mocha src/**/*.test.js --recursive --report lcovonly
> 
> No coverage information was collected, exit without writing coverage information
> C:\Users\bploszynski\Documents\GitLab\serverless-cognito-boilerplate\node_modules\.bin\_mocha.CMD:1
> (function (exports, require, module, __filename, __dirname) { @ECHO off
>                                                               ^
> 
> SyntaxError: Invalid or unexpected token
>     at new Script (vm.js:80:7)
>     at createScript (vm.js:274:10)
>     at Object.runInThisContext (vm.js:326:10)
>     at Module._compile (internal/modules/cjs/loader.js:664:28)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>     at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\bploszynski\Documents\GitLab\serverless-cognito-boilerplate\node_modules\istanbul\lib\hook.js:109:37)  
>     at Module.load (internal/modules/cjs/loader.js:600:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! serverless-cognito-boilerplate@0.1.0 test:coverage: `standard && istanbul cover _mocha src/**/*.test.js --recursive --report lcovonly`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the serverless-cognito-boilerplate@0.1.0 test:coverage script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\bploszynski\AppData\Roaming\npm-cache\_logs\2020-05-31T16_09_59_990Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! serverless-cognito-boilerplate@0.1.0 deploy: `npm run test:coverage && export SLS_DEBUG=* && serverless deploy`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the serverless-cognito-boilerplate@0.1.0 deploy script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\bploszynski\AppData\Roaming\npm-cache\_logs\2020-05-31T16_10_00_041Z-debug.log
> The terminal process terminated with exit code: 1
> 
> Terminal will be reused by tasks, press any key to close it.

**Comment by rpidanny** [comment]
what version of `node` are you using? @BartusZak
