### ISSUE TITLE
An error occurred: DataBucket - cognito-boilerplate-dev-databucket already exists.

### ISSUE THREAD

**Issue by BartusZak** [rpidanny/serverless-cognito-boilerplate#7]
> Executing task: npm run deploy <

> serverless-cognito-boilerplate@0.1.0 deploy C:\Users\bploszynski\Documents\GitLab\serverless-cognito-boilerplate
> serverless deploy

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service helloworld.zip file to S3 (19.3 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............
Serverless: Operation failed!
Serverless: View the full error output: https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-west-1%3A064454294931%3Astack%2Fcognito-boilerplate-dev%2Fe79cef20-a359-11ea-a310-0a6a2f25f2be
 
  Serverless Error ---------------------------------------
 
  An error occurred: DataBucket - cognito-boilerplate-dev-databucket already exists.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              10.15.3
     Framework Version:         1.50.0
     Plugin Version:            1.3.8
     SDK Version:               2.1.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless-cognito-boilerplate@0.1.0 deploy: `serverless deploy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serverless-cognito-boilerplate@0.1.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bploszynski\AppData\Roaming\npm-cache\_logs\2020-05-31T16_24_42_003Z-debug.log
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

**Comment by rpidanny** [comment]
Hey @BartusZak , This is because s3 bucket has to be unique and `cognito-boilerplate-dev-databucket` has already been used. I will update the naming convention to use the user's hostname to make it more unique and easy to get started. Thanks for the issue 👍
